# name: E2E tests

# on:
#   pull_request:
#     branches: ['main', 'AH-932-getAneltoCreds']

# jobs:
#   cypress-run:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Cypress E2E Tests (Chrome)
#         uses: cypress-io/github-action@v3
#         with:
#           project: ./cypress
#           browser: chrome
#           build: npm ci # was build
#           start: npm test-start
#           wait-on: 'http://localhost:5173'

# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Cypress E2E Tests (Chrome)

on:
  push:
    branches: ['main', 'dev', 'actions']
  pull_request:
    branches: ['main', 'dev', 'actions']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          browser: 'chrome'
          #project: ./cypress
          wait-on: 'http://localhost:5173'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run cypress:e2e-ci
